### PR TITLE
Add Transaction and Customer timelines

### PR DESCRIPTION
**Pull request by viceromag**

### CODE REVIEW

**Comment by pmeth** [comment]
I believe these should always be filtered by a single customer/transaction, so
customer timeline should be
`/timelines/customer/{id}`
and transactions should be
`/timelines/transaction/{id}`

**Comment by pmeth** [comment]
This looks good, however I wonder if it should instead be under the resource to which the timeline belongs, eg
`/experimental/customers/{id}/timeline`

**Comment by vova07** [comment]
I'm agree with @pmeth !
it make sense to have this timeline as part of main resource `customers` or `transactions`.

**Comment by pmeth** [comment]
If we move `customers` and `transactions` then I think it makes sense to move global to `/global-timeline`. No sense having `/timelines/global`

**Pull request merged**
